language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without tools
script:
  - bundle exec rake spec
after_script:
  - bundle exec codeclimate-test-reporter
rvm:
  - 2.4.0
  - 2.3
  - 2.2
  - rbx-3
  - jruby-0.1.6.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
